apiVersion: v1
kind: Service
metadata:
  name: {{ include "glpi.fullname" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "glpi.selectorLabels" . | nindent 4 }}
